FROM node:20-alpine

WORKDIR /app

# Install bash and other useful tools
RUN apk add --no-cache bash

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "start"]